# Necessário baixar o prometheus, extrair o arquivo do wget e o executar
# Arquivo de configuração do Prometheus

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
